name: build

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
     - 'Obligatorio/codigo/ArenasGestor/**.cs'
     - 'Obligatorio/codigo/ArenasGestor/**/*.csproj'
     - 'Obligatorio/codigo/ArenasGestor/*.sln'
     
env:
  DOTNET_VERSION: '5.0' # The .NET SDK version to use

jobs:
  build:
    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore Dependencies
      run: dotnet restore Obligatorio/codigo/ArenasGestor/*.sln

    - name: Build
      run: dotnet build Obligatorio/codigo/ArenasGestor/*.sln --configuration Release
