name: Selenium Tests
on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]
jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install Chrome WebDriver
        run: npm install webdriver-manager -g

      - name: Update WebDriver Manager and Install Dependencies
        run: |
          npm install -g webdriver-manager
          webdriver-manager update --versions.chrome=$(google-chrome-stable --version | awk '{ print $3 }' | awk -F. '{ printf "%s.%s", $1, $2 }') --gecko=false
        working-directory: ./Obligatorio/codigo/ArenaGestorFront/

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Build Angular app
        run: ng build --prod
        working-directory: ./Obligatorio/codigo/ArenaGestorFront/

      - name: Install dependencies
        run: npm install
        working-directory: ./Obligatorio/codigo/ArenaGestorFront/

      - name: Run Selenium tests
        run: |
          npm install -g selenium-side-runner
          selenium-side-runner ISA2_Test_De_Selenium_Entrega_4.side
        working-directory: ./Obligatorio/TestsDeSelenium
